#!/usr/bin/env bash
# Fix Ubuntu container from listening on port 80
to_replace="listen 8080 default_server;"
replace="listen 80 default_server;"
sed -i "s/$to_replace/$replace/" /etc/nginx/sites-enabled/default
sudo service nginx restart 
