#!/usr/bin/env bash
# This script displays numbers from 1 to 100

i=1
max=100
while [ $i -le $max ]; do
	if [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]; then
		echo "FizzBuzz"
	elif [ $((i % 3)) -eq 0 ]; then
		echo "Fizz"
	elif [ $((i % 5)) -eq 0 ]; then
		echo "Buzz"
	else
		echo "$i"
	fi
	i=$((i + 1))
done
