#!/usr/bin/env bash
# This script displaying numbers from 1 to 20. Displays 4 and bad luck from China for the 4th loop iteration. Displays 9 and then bad luck from Japan for the 9th loop iteration. Displays 17 and then bad luck from Italy for the 17th loop iteration.

i=1
max=20
while [ $i -le $max ]; do
	echo "$i"
	case $i in
		4) echo "bad luck from China" ;;
		9) echo "bad luck from Japan" ;;
		17) echo "bad luck from Italy" ;;
	esac
	i=$((i + 1))
done
