#!/usr/bin/env bash
# This script gives information about the holbertonschool file

file_name="holbertonschool"
if [ -e $file_name ]; then
	echo "holbertonschool file exists"

	if [ -s $file_name ]; then
		echo "holbertonschool file is not empty"
	else
		echo "holbertonschool file is empty"
	fi

	if [ -f $file_name ]; then
		echo "holbertonschool is a regular file"
	fi
else
	echo "holbertonschool file does not exist"
fi
