#!/usr/bin/env bash
# Run nginx as nginx user
sudo pkill apache2
if ! id -u nginx > /dev/null 2>&1; then
	useradd nginx
fi
sudo chown -R nginx:nginx /etc/nginx
sudo chmod -R 750 /etc/nginx
sudo sed -i "s/user www-data;/user nginx;/" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
