#!/usr/bin/env bash
# Short and sweet - configuration of nginx
sudo pkill apache2
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo chown -R nginx:nginx /etc/nginx
sudo chmod -R 750 /etc/nginx.conf
sudo -u nginx service nginx restart
